
<!DOCTYPE html>
<html>
	<head>
		<title>Compra de Producto</title>
	</head>
	<body>
		<section>
			<?php View::content();?>
			<?php echo Form::open();?>
			<form>
				<h3 id="us">Compra de producto</h3>
				<table cellspacing="10px">
					<tr>
						<td>
							<label><i>Id Compra</i></label>
						</td>
						<td>
							<label><?php echo Form::text('CompraProducto.idCompraProducto')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Id Cliente</i></label>
						</td>
						<td>
							<label><?php echo Form::select('CompraProducto.idCliente',array(1=>'Kevin',2=>'David  '))?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>id Producto</i></label>
						</td>
						<td>
							<label><?php echo Form::select('CompraProducto.idProducto',array(1=>'Perfume',2=>'Aros', 3=>'Radios'))?></label>
						</td>
					</tr>
					
					<tr>
						<td>
							<label><i>Fecha</i></label>
						</td>
						<td>
							<label><?php echo Form::date('CompraProducto.fecha')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Costo</i></label>
						</td>
						<td>
							<label><?php echo Form::text('CompraProducto.totalPago')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<?php echo Form::submit (' Guardar ') ?>
						</td>
					</tr>
				</table>
			</form>
			<?php Form::close() ?>
		</section>
	</body>
</html>