<!DOCTYPE html>
<html>
<head>
	<title>Pago Servicio</title>
</head>
<body>
	<?php View::content();?>
			<?php echo Form::open();?>
			<form>
				<h3 id="us" align="Center">Pago Servicio</h3>
				<table cellspacing="10px" class="condensed , zebra ,  t">
					<tr>

					</tr>
					<tr>
						<td>
							<label><i>Cliente</i></label>
						</td>
						<td>
							<label><?php echo Form::select('Pago.idCliente',array($listvar1->idCliente=>$listvar1->nombreCliente))?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Service ID</i></label>
						</td>
						<td>
							<label><?php echo Form::Select('Pago.idServicio',array($listvar3->idServicio=>$listvar3->idServicio))?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Contrato-Servicio</i></label>
						</td>
						<td>

							<label><?php echo Form::select('Pago.idContrato',array($listvar2=>$listvar3->nombre)) ?></label>
							<!--<label><?php echo Form::select('Pago.idContrato',array(1=>'Kevin',2=>'David  '))?></label>-->
						</td>
					</tr>
					<tr>
						<td>
							<label><i>PAGO</i></label>
						</td>
						<td>
							
							<label><?php echo Form::select('Pago.totalPago', array($listvar3->precio => $listvar3->precio ))?></label>
						</td>
					</tr>
					
					<tr>
						<td>
							<label><i>Fecha</i></label>
						</td>
						<td>
							<label><?php echo Form::date('Pago.fecha')?></label>
						</td>
					</tr>

					<tr>	
						<td>
							<?php echo Form::submit (' Guardar ') ?>
						</td>
					</tr>
				</table>
			</form>
			<?php Form::close() ?>

</body>
</html>