<!DOCTYPE html>
<html>
<head>
	<title>Pago Servicio</title>
</head>
<body>
	<?php View::content();?>
	<?php echo Form::open();?>
	<form>
		<h3 id="us" align="Center">Servicio y producto mas vendidos</h3>
		<table cellspacing="10px" class="condensed , zebra ,  t">

			<tr>
				<td>
					<label><i>Servicio - Producto</i></label>
				</td>
			</tr>
			<tr>
				<td>
					<label><i>Fecha inicio</i></label>
				</td>
				<td>
					<label><?php echo Form::date('Comparacion.fechaDesde')?></label>
				</td>
			</tr>			
			<tr>
				<td>
					<label><i>Fecha Final</i></label>
				</td>
				<td>
					<label><?php echo Form::date('Comparacion.fechaHasta')?></label>
				</td>
			</tr>				
	
			<tr>
			


				<td>
					<?php echo Form::submit (' Guardar ') ?>
				</td>
			</tr>
		</table>
	</form>
	<?php Form::close() ?>

</body>
</html>