
<!DOCTYPE html>
<html>
	<head>
		<title>Analisis</title>
		<?php 
			echo Tag::js('jquery/jquery.min');
			echo Tag::js('jquery/jquery.kumbiaphp.min');
				
		?>
	</head>
	<body>
		<section>
			<?php View::content();?>
			<h3 align="center">Servicio y Producto mas vendido</h3>
			<table id="tabla" class="condensed , zebra , border , t">
				<tr>
					<th class="tab"><i>#Comparacion</i></th>
					<th class="tab"><i>Servicio</i></th>
					<th class="tab"><i>Ganancias </i></th>
					 <!-- <th class="tab"><i>Password</i></th> -->
					 <th class="tab"><i>Producto</i></th>
					<th class="tab"><i>Ganancias</i></th>



				</tr>
				<tr>
					<td class="tab" align="center"><?php echo $idc ?></td>
					<td class="tab" align="center"><?php echo $listservicio ?></td>
					<td class="tab" align="center"><?php echo $listsql ?></td>
					<td class="tab" align="center"><?php echo $listproducto ?></td>
					
					<td class="tab" align="center"><?php echo $vsql ?></td>
				</tr>
				
				
			</table>
			<br/>
			<div class="col-3 text-right">
	            <ul class="inline" >
	              <li><a href='http://localhost/talleresphp/Comparacion/ProductoServicioVendido'> Consultar de nuevo </a> |</li>
	              <li><a href='http://localhost/talleresphp/Comparacion/index'>Inicio</a> |</li>
	             
	            </ul>
          	</div>	
			<a href="http://localhost/talleresphp/" aria-current="page" class="col-2 text-right">
				Cerrar sesion
			</a>
			<br/>

		
		</section>
	</body>
</html>