
<!DOCTYPE html>
<html>
	<head>
		<title>Editar Servicio</title>
	</head>
	<body>
		<section>
			<?php View::content();?>
			<?php echo Form::open();?>
			<form>
				<h3 id="us">Editar Servicio</h3>
				<table cellspacing="10px">
					<tr>
						<td>
							<label><?php echo Form::hidden('Servicio.idServicio')  ?></label>
						</td>
					</tr>
					<tr>
						
						<td>
							<label><i>Nombre</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Servicio.nombre')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Precio</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Servicio.precio')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<?php echo Form::submit (' Actualizar ') ?>
						</td>
					</tr>
				</table>
			</form>
			<?php Form::close() ?>
		</section>
	</body>
</html>