
<!DOCTYPE html>
<html>
	<head>
		<title>Editar Usuario</title>
	</head>
	<body>
		<section>
			<?php View::content();?>
			<?php echo Form::open();?>
			<form>
				<h3 id="us" align="Center">Editar Usuario</h3>
				<table cellspacing="10px" class="condensed , zebra  , t">
					<tr>
						<td>
							<label><?php echo Form::hidden('Cliente.idCliente')  ?></label>
						</td>
					</tr>
					<tr>
						
						<td>
							<label><i>Nombre</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Cliente.nombreCliente')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Password</i></label>
						</td>
						<td>
							<label><?php echo Form::pass('Cliente.password')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Genero</i></label>
						</td>
						<td>
							<label><i>M</i><?php echo Form::radio('Cliente.genero','M','Cliente.genero')?></label>
							<label><i>F</i><?php echo Form::radio('Cliente.genero','F','Cliente.genero')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Fecha Nacimiento</i></label>
						</td>
						<td>
							<label><?php echo Form::date('Cliente.fechaNacimiento')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Email</i></label>
						</td>
						<td>
							<label><?php echo Form::email('Cliente.email')?></label>
						</td>
					</tr>
					<tr>
					<tr>
						<td>
							<label><?php echo Form::hidden('Cliente.rol')  ?></label>
						</td>
					</tr>
					<tr>

					<tr>
						<td>
							<?php echo Form::submit (' Actualizar ') ?>
						</td>
					</tr>
				</table>
			</form>
			<?php Form::close() ?>
		</section>
	</body>
</html>