
<!DOCTYPE html>
<html>
	<head>
		<title>Login ADMIN</title>
		
		<!--<?php Tag::css('kumbia')?>-->
	</head>
	<body>
		<h3>Login Admin</h3>
		<section>

			<?php View::content(); ?>
			<?php echo Form::open("Cliente/login"); ?> <!--Estaba usuario/index/-->
			<?php echo Form::label("Cliente","login"); ?><!--Estaba "email"-->
			<?php echo Form::email("email"); ?>
			<?php echo Form::label("Password","password"); ?>
			<?php echo Form::pass("password"); ?>
			<br>
			<?php echo Form::submit("Ingresar"); ?>
			<?php echo Form::close(); ?>
			<br/>
			<p class="links"><?php echo Html::linkAction("create/",'Registrarme') ?></p>
			
			<br>
				

			<br/>

		</section>
	</body>
</html>