
<!DOCTYPE html>
<html>
	<head>
		<title>Quiero el producto</title>
	</head>
	<body>
		<section>
			<?php View::content();?>
			<?php echo Form::open();?>
			<form>
				<h3 id="us">Producto</h3>
				<table cellspacing="10px">
					<tr>
						<td>
							<label><?php echo Form::hidden('Producto.idProducto')  ?></label>
						</td>
					</tr>
					<tr>
						
						<td>
							<label><i>Nombre</i></label>
						</td>
						<td>
							<label><?php print(Form::text('Producto.nombre'))  ?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Precio</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Producto.precio')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Cantidad</i></label>
						</td>
						<td>
							<form method="post" action="action.php">
								<input name="ingresatexto" type="text" value=" " />
							</form>
						</td>
					</tr>
					<tr>
						<td>
							<?php echo Form::submit (' Aceptar ') ?>
						</td>
					</tr>
				</table>
			</form>
			<?php Form::close() ?>
		</section>
	</body>
</html>