
<!DOCTYPE html>
<html>
	<head>
		<title>Anadir Producto</title>
	</head>
	<body>
		<section>
			<?php View::content();?>
			<?php echo Form::open();?>
			<form>
				<h3 id="us" align="Center">Anadir Producto</h3>
				<table cellspacing="10px" class="condensed , zebra ,  t">
					<tr>
						<td>
							<label><i>Nombre</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Producto.nombre')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Precio</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Producto.precio')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Stock</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Producto.stock')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<?php echo Form::submit (' Guardar ') ?>
						</td>
					</tr>
				</table>
			</form>
			<?php Form::close() ?>
		</section>
	</body>
</html>