
<!DOCTYPE html>
<html>
	<head>
		<title>Compra de Producto</title>
	</head>
	<body>
		<section>
			<?php View::content();?>
			<?php echo Form::open();?>
			<form>
				<h3 id="us" align="Center">Compra de producto</h3>
				<table cellspacing="10px" class="condensed , zebra ,  t">
					<tr>
						<td>
							<label><i>Id Compra</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Compra.idCompra')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Id Cliente</i></label>
						</td>
						<td>
							<label><?php echo Form::select('Compra.idCliente',array(1=>'Kevin',2=>'David  '))?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>id Producto</i></label>
						</td>
						<td>
							<label><?php echo Form::select('Compra.idProducto',array(1=>'Perfume',2=>'Aros', 3=>'Radios'))?></label>
						</td>
					</tr>
					
					<tr>
						<td>
							<label><i>Fecha</i></label>
						</td>
						<td>
							<label><?php echo Form::date('Compra.fecha')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<label><i>Costo</i></label>
						</td>
						<td>
							<label><?php echo Form::text('Compra.totalPago')?></label>
						</td>
					</tr>
					<tr>
						<td>
							<?php echo Form::submit (' Guardar ') ?>
						</td>
					</tr>
				</table>
			</form>
			<?php Form::close() ?>
		</section>
	</body>
</html>